###################
# This is property of eXtremeSHOK.com
# You are free to use, modify and distribute, however you may not remove this notice.
# Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
# License:             BSD (Berkeley Software Distribution)
##################
matrix:
  include:
#### MARKDOWN-LINT
    - language: node_js
      os: linux
      dist: focal
      before_install:
       - nvm install 14.6.0
       - nvm use 14.6.0
      install:
      - npm install --global markdownlint-cli
      script:
      - markdownlint *.md
#### SHELLCHECK
    - language: shell
      os: linux
      dist: focal
      install:
      - sudo apt-get install -y shellcheck -qq
      script:
      - sudo sh -e .t/ci-shellcheck.sh
#### LOGIC AND CLAMAV TESTING : UBUNTU LINUX
    - language: shell
      os: linux
      dist: focal
      # Required travis ci environment variables
      #ci_malwareexpert_serial_key=[secure]
      #ci_securiteinfo_authorisation_signature=[secure]
      #ci_malwarepatrol_receipt_code=[secure]
      #ci_malwarepatrol_product_code=[secure]
      #ci_malwarepatrol_list=[secure]
      #ci_malwarepatrol_free=[secure]
      #ci_codeclimate_repo_token=[secure]
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y ca-certificates curl wget rsync p7zip-full -qq
        - sudo apt-get install -y clamav-base clamav-freshclam clamav clamav-daemon -qq
      install:
        - sudo mkdir -p /etc/clamav-unofficial-sigs
        - sudo cp -f config/master.conf /etc/clamav-unofficial-sigs/master.conf
        - sudo cp -f config/os/os.ubuntu.conf /etc/clamav-unofficial-sigs/os.conf
        - sudo cp -f clamav-unofficial-sigs.sh /usr/sbin/clamav-unofficial-sigs
      script:
        - sudo sh -e .t/ci-clamav-download-default-databases.sh
        #- sudo sh -e .t/ci-clamav-download-default-databases-git.sh
        - sudo sh -e .t/ci-clamav-install-ubuntu-databases.sh
        - sudo cp -f .t/tests/user.conf /etc/clamav-unofficial-sigs/user.conf
        - sudo sh -e .t/ci-test-ubuntu.sh
      addons:
        code_climate:
          repo_token:  $ci_codeclimate_repo_token
#### LOGIC AND CLAMAV TESTING : macOS / OSX
    - os: osx
      osx_image: xcode12
      before_cache:
        - brew cleanup
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      # addons:
      #     homebrew:
      #       packages:
      #       - gnu-tar
      #       - gnu-sed
      #       - clamav
      before_install:
        - homebrew update
        - homebrew install gnu-tar gnu-sed clamav        
      install:
        - sudo mkdir -p /usr/local/bin
        - sudo mkdir -p /usr/local/etc/clamav-unofficial-sigs
        - sudo cp -f clamav-unofficial-sigs.sh /usr/local/bin/clamav-unofficial-sigs.sh
        - sudo chmod 755 /usr/local/bin/clamav-unofficial-sigs.sh
        - sudo cp -f config/master.conf /usr/local/etc/clamav-unofficial-sigs/master.conf
        - sudo cp -f config/os/os.macos.conf /usr/local/etc/clamav-unofficial-sigs/os.conf

      script:
        - sudo sh -e .t/ci-clamav-download-default-databases.sh
        #- sudo sh -e .t/ci-clamav-download-default-databases-git.sh
        - sudo sh -e .t/ci-clamav-install-macos-clamav.sh
        - sudo sh -e .t/ci-clamav-install-macos-databases.sh
        - sudo cp -f .t/tests/user.conf /usr/local/etc/clamav-unofficial-sigs/user.conf
        - sudo sh -e .t/ci-test-macos.sh
